### PR TITLE
composer robo database:download on a Windows machine might crash depending on filename of DB-dump

### LINKED ISSUE #62: composer robo database:download on a Windows machine might crash depending on filename used on AWS
Currently the filename that's used for downloading a DB-Dump from AWS S3 can contain characters that are Windows unfriendly, like a colon(`:`).

If such a filename occurs doing a `composer robo database:download` on a Windows machine _might_ start The Apocalypse, but at the very least crashes with:

```
ERROR: stream_copy_to_stream() expects parameter 2 to be resource, bool given
in \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php:68

PHP Warning:  stream_copy_to_stream() expects parameter 2 to be resource, bool given in \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php on line 68
PHP Stack trace:
PHP   1. {main}() \path\to\vendor\bin\robo:0
PHP   2. include() \path\to\vendor\bin\robo:112
PHP   3. Robo\Runner->execute() \path\to\vendor\consolidation\robo\robo:48
PHP   4. Robo\Runner->run() \path\to\vendor\consolidation\robo\src\Runner.php:158
PHP   5. Robo\Application->run() \path\to\vendor\consolidation\robo\src\Runner.php:282
PHP   6. Robo\Application->doRun() \path\to\vendor\symfony\console\Application.php:149
PHP   7. Robo\Application->doRunCommand() \path\to\vendor\symfony\console\Application.php:273
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->run() \path\to\vendor\symfony\console\Application.php:1027
PHP   9. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() \path\to\vendor\symfony\console\Command\Command.php:255
PHP  10. Consolidation\AnnotatedCommand\CommandProcessor->process() \path\to\vendor\consolidation\annotated-command\src\AnnotatedCommand.php:350
PHP  11. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:176
PHP  12. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:212
PHP  13. call_user_func_array:{\path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257}() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257
PHP  14. Usher\Robo\Plugin\Commands\Drupal7DevelopmentModeCommands->databaseDownload() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257
PHP  15. stream_copy_to_stream() \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php:68
```

This PR tries to be inclusive to our Windows-using friends: https://github.com/ChromaticHQ/usher/pull/61

### PR DESCRIPTION
**Pull request by Boegie**
Sanitize filename for Windows.

Currently the filename that's used for downloading a DB-Dump from AWS S3 can contain characters that are Windows unfriendly, like a colon(`:`).

If something likes that occurs doing a `composer robo database:download` on a Windows machine _might_ start The Apocalypse, but at the very least crashes with:

```
ERROR: stream_copy_to_stream() expects parameter 2 to be resource, bool given
in \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php:68

PHP Warning:  stream_copy_to_stream() expects parameter 2 to be resource, bool given in \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php on line 68
PHP Stack trace:
PHP   1. {main}() \path\to\vendor\bin\robo:0
PHP   2. include() \path\to\vendor\bin\robo:112
PHP   3. Robo\Runner->execute() \path\to\vendor\consolidation\robo\robo:48
PHP   4. Robo\Runner->run() \path\to\vendor\consolidation\robo\src\Runner.php:158
PHP   5. Robo\Application->run() \path\to\vendor\consolidation\robo\src\Runner.php:282
PHP   6. Robo\Application->doRun() \path\to\vendor\symfony\console\Application.php:149
PHP   7. Robo\Application->doRunCommand() \path\to\vendor\symfony\console\Application.php:273
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->run() \path\to\vendor\symfony\console\Application.php:1027
PHP   9. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() \path\to\vendor\symfony\console\Command\Command.php:255
PHP  10. Consolidation\AnnotatedCommand\CommandProcessor->process() \path\to\vendor\consolidation\annotated-command\src\AnnotatedCommand.php:350
PHP  11. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:176
PHP  12. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:212
PHP  13. call_user_func_array:{\path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257}() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257
PHP  14. Usher\Robo\Plugin\Commands\Drupal7DevelopmentModeCommands->databaseDownload() \path\to\vendor\consolidation\annotated-command\src\CommandProcessor.php:257
PHP  15. stream_copy_to_stream() \path\to\vendor\chromatic\usher\src\Robo\Plugin\Traits\DatabaseDownloadTrait.php:68
```

This PR tries to be inclusive to our Windows-using friends.

### CODE REVIEW

**Comment by adamzimmermann** [comment]
A detailed ticket and a PR already. I love it! 💯

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function databaseDownload(string $siteName = 'default')
         // Ensure objects are sorted by last modified date.
         usort($objects, fn($a, $b) => $a->getLastModified()->getTimestamp() <=> $b->getLastModified()->getTimestamp());
         $latestDatabaseDump = array_pop($objects);
-        $dbFilename = $latestDatabaseDump->getKey();
+        $dbFilename = $this->sanitizeFileNameForWindows($latestDatabaseDump->getKey());
```
Comment (adamzimmermann) [inline src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: Will this break line 65 since we are changing the filename that we send to S3 to tell it what we want to download?

Or what am I not understanding correctly?

Also, if you have tested this successfully and can confirm it's not an issue let me know!

`composer require chromatichq/usher:dev-YOUR-BRANCH-NAME`

**Review by adamzimmermann — COMMENTED** [review]
The `sanitizeFileNameForWindows` method looks solid. I love all of the code comments. I have a few questions about some others things though.

Is there a reason you forked this repo to make the change vs just using a branch? We typically use the branch workflow. This explains it a bit more, let me know if you have questions.

- https://almanac.io/docs/development-qa-workflow-8LSXNToH3ynV7ZDw6EYh0V08vNNBlFZE

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php (hunk 1 above)
Comment (Boegie) [reply src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: Thanks @adamzimmermann for the review.

> Is there a reason you forked this repo to make the change vs just using a branch? 
Newbees gonna newbee... (Never occurred to me I could directly create a branch, since I'm now a proud member of the Chromatic GitHub repos) 

Also thanks for putting your name as reviewer. If I would have remembered the correct workflow, I would have struggled finding the correct people/person.

> Will this break line 65 since we are changing the filename that we send to S3 to tell it what we want to download?

EDIT: Sorry for the noise, I'm used to GitLab, which does things slightly different. I'll answer this question in the next comment

Comment (Boegie) [reply src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: @adamzimmermann You were absolutely right, I've managed to mess it up in my fork already. 

This version works for me and _should_ leave non-Windows environments alone.

Comment (adamzimmermann) [reply src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: > If I would have remembered the correct workflow, I would have struggled finding the correct people/person.

Feel free to add me to any back-end PR's. If there is someone better for a given project I'll point you in the right direction! Also feel free to ask around in Slack.

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php [hunk 2]
```diff
@@ -169,4 +170,34 @@ protected function s3RegionForSite(string $siteName): string
...
+     *
+     * @param string $fileName
+     *   The file name to sanitize.
+     *
+     * @return string
+     *   The sanitized filename.
+     */
+    public function sanitizeFileNameForWindows(string $fileName): string
+    {
+        if (PHP_OS_FAMILY === 'Windows') {
```
Comment (adamzimmermann) [inline src/Robo/Plugin/Traits/DatabaseDownloadTrait.php:185]: I had no idea there were constants with this information. Very cool.

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php [hunk 3]
```diff
@@ -56,19 +56,20 @@ public function databaseDownload(string $siteName = 'default')
         usort($objects, fn($a, $b) => $a->getLastModified()->getTimestamp() <=> $b->getLastModified()->getTimestamp());
         $latestDatabaseDump = array_pop($objects);
         $dbFilename = $latestDatabaseDump->getKey();
+        $localFilename = $this->sanitizeFileNameForWindows($dbFilename);
```
Comment (adamzimmermann) [inline src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: What are your thoughts on naming this something like `$downloadFileName` to help reinforce how it's being used?

**Review by adamzimmermann — COMMENTED** [review]
Looking good! One last question.

Also, can you add some screenshots of this in action in your CLI?

I'm tagging in @markdorison too since he helped write a lot of this tooling, so I'm sure he will want to stay up to date on the changes.

**Review by markdorison — COMMENTED** [review]
Love this improvement!

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php (hunk 2 above)
Comment (Boegie) [reply src/Robo/Plugin/Traits/DatabaseDownloadTrait.php:185]: Me neither, develop-by-Google FTW

File: src/Robo/Plugin/Traits/DatabaseDownloadTrait.php (hunk 3 above)
Comment (Boegie) [reply src/Robo/Plugin/Traits/DatabaseDownloadTrait.php]: Shamelessly playing the Non-Native-Speaker card here. (And yes, looking at it that's a much better name)

**Comment by adamzimmermann** [comment]
@Boegie if this is ready for a final review, our standard process is to re-request a review with the little circle icon.


Screen Shot 2022-03-07 at 8 37 45 AM

**Comment by Boegie** [comment]
Screenshot _without_ the changes in this PR: 

image

**Comment by Boegie** [comment]
I can't seem to pull in an PR in `composer`, so I used the `HEAD` of `Boegie/usher` (which is this PR).

Screenshot of `composer robo database:download` this time:
image

**Comment by Boegie** [comment]
Thanks @adamzimmermann, should I also re-request a review from Mark?

**Comment by adamzimmermann** [comment]
> Thanks @adamzimmermann, should I also re-request a review from Mark?

Always feel free to re-request review from anyone who you think might have valuable feedback for your PR!

**Review by adamzimmermann — APPROVED** [review]

**Review by markdorison — APPROVED** [review]
